# Generated by Django 5.0.7 on 2024-07-30 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team1',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='date_played',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='best_of',
            new_name='total_rounds',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='team1_score',
            new_name='score_team1',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='team2_score',
            new_name='score_team2',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='side',
            new_name='side_played',
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('team1', 'Team 1'), ('team2', 'Team 2')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='winning_team',
            field=models.CharField(choices=[('team1', 'Team 1'), ('team2', 'Team 2')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Forwards', 'Forwards'), ('Backwards', 'Backwards')], max_length=10)),
                ('team', models.CharField(choices=[('team1', 'Team 1'), ('team2', 'Team 2')], max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
