# Generated by Django 5.0.7 on 2024-07-30 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_round_round_number_alter_round_score_team1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='team1_players',
            field=models.ManyToManyField(blank=True, related_name='team1_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_players',
            field=models.ManyToManyField(blank=True, related_name='team2_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
