# Generated by Django 5.0.7 on 2024-07-30 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_status_game_team1_players_game_team2_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='team1_players',
            field=models.ManyToManyField(blank=True, related_name='team1_players', to='games.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team2_players',
            field=models.ManyToManyField(blank=True, related_name='team2_players', to='games.player'),
        ),
        migrations.AlterField(
            model_name='playergame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_games', to='games.player'),
        ),
    ]
