# Generated by Django 5.0.7 on 2024-07-31 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_player_alter_game_team1_players_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='date_played',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team1_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='total_rounds',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_score', models.IntegerField()),
                ('right_score', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.game')),
                ('left_defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_defense_matches', to='games.player')),
                ('left_offense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_offense_matches', to='games.player')),
                ('right_defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_defense_matches', to='games.player')),
                ('right_offense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_offense_matches', to='games.player')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerGame',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
