# Generated by Django 5.0.7 on 2024-07-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_round_game_remove_game_date_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
