# Generated by Django 5.0.7 on 2024-08-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
